#!/bin/bash

#PBS -l select=1:ncpus=16:mpiprocs=8:mem=10GB
#PBS -l walltime=06:00:00
#PBS -q queue_to_use
#PBS -N PROCESS_NAME
#PBS -o filename_out
#PBS -e filename_err

#choose working directory
cd $PBS_O_WORKDIR

#load necessary modules, lammps in the present configuration is installed locally
# (user) and not needed to be loaded
#module load lammps
module load gcc75
module load mpich-3.2
module load python-3.7.2

#source necessary apps - bug fix for modules not loading correctly
source /apps/Python-3.7.2/bin/

#set variable equal to the number of nucleotides of the RNA fragment being simulated
VAR=735

# Configure the lammps input script to correspond to the 
# correct length of nucleotide chain being simulated
sed -i "4s/.*/variable number equal ${VAR}/" ./../input_scripts/input_extend.lammps

#run the simulation - extension
lmp -in ./../input_scripts/input_extend.lammps
