#!/bin/bash

#PBS -l select=1:ncpus=16:mpiprocs=8:mem=10GB
#PBS -l walltime=06:00:00
#PBS -q queue_to_use
#PBS -N PROCESS_NAME
#PBS -o filename_out
#PBS -e filename_err

#choose working directory
cd $PBS_O_WORKDIR

#load necessary modules, lammps in the present configuration is installed locally
# (user) and not needed to be loaded
#module load lammps
module load gcc75
module load mpich-3.2
module load python-3.7.2

#source necessary apps - bug fix for modules not loading correctly
source /apps/Python-3.7.2/bin/

#run the commands/scripts
./main.sh


# This script is used to start the simulation - see the main.sh script.
# In case the script needs to run non-continuously, or the simulations started with this 
# script need to be extended, there exists a secondary extension script.